---
- name: Deploy web application
  hosts: mns
  become: yes
  tasks:
    - name: Ensure NGINX is installed
      dnf:
        name: nginx
        state: present

    - name: Copy application HTML file
      copy:
        src: /opt/devops-lab/devops-lab/index.html
        dest: /usr/share/nginx/html/index.html
        mode: 0644

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
