---
- name: Deploy web application
  hosts: webservers
  become: yes
  tasks:
    - name: Copy app from Jenkins workspace
      copy:
        src: /var/lib/jenkins/workspace/ci_cd_lab_app/index.html
        dest: /usr/share/nginx/html/index.html
        mode: 0644
